# Generated by Django 5.2.14 on 2026-05-22 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_name', models.CharField(default='registration_extraction_v1', max_length=100)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='documents.documentupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
